### ISSUE TITLE
Error on MPV 0.32

### ISSUE THREAD

**Issue by danilovicente** [yuukidach/mpv-scripts#1]
Hey man, I love your script. I'm getting this error. If i remove the line is messing up it works, but is not saving the time properly. I don't know if there's something related to the watch-later config. Can u give me some light? I really appreciate.

```
[history_bookmark]
[history_bookmark] stack traceback:
[history_bookmark]      /home/dan/.config/mpv/scripts/history-bookmark.lua:111: in function 'create_playlist'
[history_bookmark]      /home/dan/.config/mpv/scripts/history-bookmark.lua:221: in function 'handler'
[history_bookmark]      mp.defaults:486: in function 'call_event_handlers'
[history_bookmark]      mp.defaults:520: in function 'dispatch_events'
[history_bookmark]      mp.defaults:479: in function <mp.defaults:478>
[history_bookmark]      [C]: at 0x55c9bf49ddb0
[history_bookmark]      [C]: at 0x55c9bf49f0f0
[history_bookmark] Lua error: /home/dan/.config/mpv/scripts/history-bookmark.lua:111: bad argument #1
to 'sort' (table expected, got nil)
```

**Comment by danilovicente** [comment]
> Hey man, I love your script. I'm getting this error. If i remove the line is messing up it works, but is not saving the time properly. I don't know if there's something related to the watch-later config. Can u give me some light? I really appreciate.
> 
> ```
> [history_bookmark]
> [history_bookmark] stack traceback:
> [history_bookmark]      /home/dan/.config/mpv/scripts/history-bookmark.lua:111: in function 'create_playlist'
> [history_bookmark]      /home/dan/.config/mpv/scripts/history-bookmark.lua:221: in function 'handler'
> [history_bookmark]      mp.defaults:486: in function 'call_event_handlers'
> [history_bookmark]      mp.defaults:520: in function 'dispatch_events'
> [history_bookmark]      mp.defaults:479: in function <mp.defaults:478>
> [history_bookmark]      [C]: at 0x55c9bf49ddb0
> [history_bookmark]      [C]: at 0x55c9bf49f0f0
> [history_bookmark] Lua error: /home/dan/.config/mpv/scripts/history-bookmark.lua:111: bad argument #1
> to 'sort' (table expected, got nil)
> ```

I realized the error shows when there's no history file in the folder.

**Comment by yuukidach** [comment]
@danilovicente 

Hi, thanks for your feedback.

I looked through the code for the problem you mentioned. But it does not seem to be related to the history file.

Can you provide more detailed process about how you encountered this problem?

**Comment by danilovicente** [comment]
@yuukidach 

Thanks for your reply. Never mind the problem I mentioned, it's working fine. Was a conflict with my config. I really apreciate. Thanks.

**Comment by danilovicente** [comment]
I don't wanna bother you, but there's a thing. When I press enter to continue the last episode, it clean the playlist and open the last file I played. And even when I press N to not continue, if later on I press ENTER it's jumps back to this file.

**Comment by yuukidach** [comment]
@danilovicente 

I tried as you said and also met this problem. I'll fix it as soon as possible when I have time.

When you find other problem, just leave a message to me. And I'm really happy that you can use this script.

Thank you.

**Comment by yuukidach** [comment]
Hi, @danilovicente . 

Sorry for replying you so late. 

I had some works to do during the last 2 weeks. Just now I fixed the problem you mentioned.

**Comment by danilovicente** [comment]
Thanks man. :+1:
